### ISSUE TITLE
[v2] Unable to log in to DGS

### ISSUE THREAD

**Issue by andybalaam** [cerisara/DragonGoApp#12]
I downloaded the apk from http://talc1.loria.fr/users/cerisara/DragonGoAppv2.apk and installed.

Then I chose the menu, Settings.

I entered my username and password, but received an error saying it was unable to log in.  I tried it a few times so I am fairly sure I got the password right!

The error message almost implied to me that it was trying to use the username as the password...

**Comment by cerisara** [comment]
Also can't reproduce :-(
I just pressed "...", then "set login/password", then enter my login, then my password,
and everything worked just fine.

may be this: if you type wrong credentials the first time, then you must input next time again *both* your login + password. That may be the reason it was not working for you...

**Comment by cerisara** [comment]
Otherwise, you may search in the adb logcat output the string:
"debug login cmd"
this line contains the login command that is sent to the DGS server.

**Comment by andybalaam** [comment]
Hmm. I definitely typed username and password each time. Again, I will try to reproduce it when I get time.

**Comment by andybalaam** [comment]
I'm sorry I never responded on the issues I logged.  The app is working really well for me, and I am incredibly grateful for your work.

**Comment by cerisara** [comment]
Thanks a lot for your feedback !
Best
