### ISSUE TITLE
Can't find menu/settings

### ISSUE THREAD

**Issue by ludogre** [cerisara/DragonGoApp#16]
Hi!

I'm using the v1.10 version of this app on android 7.1.2.
I want to login to dgs, but I can't find the menu/settings that is required to do it.

**Comment by cerisara** [comment]
Hi,

Yes, I'm sorry, the version of the app that is on F-Droid has not been updated and is *really* for old smartphones, and on most "recent" smartphones, the menu is not visible any more.
I've modified the latest versions of the app to make the "settings" menu visible on recent smartphones, but it's not on F-Droid. I've recompiled the apk and deployed it on another server of mine; I've also updated the links on the app web page and github README to point to this new server.

So I suggest you use the apk that you can download from the links on the app page, or recompile the apk yourself.

Sorry for the delay to answer - I should enable email notifications on this repo...
